project/urls.py
import django.contrib.auth.views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/logout/', django.contrib.auth.views.LogoutView, name="logout"),
    path("", include("snaver.urls")),
    path("", include("accounts.urls")),
    path("", include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

snaver/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.urls import re_path

from snaver import views
# from snaver.views import ChartsListView
from snaver.views import BudgetView
from snaver.views import ReportsListView
from snaver.views import TransactionCreateView
from snaver.views import TransactionListView

urlpatterns = [
    path('', login_required(BudgetView.as_view()), name='home'),
    path('', views.index, name='logout'),
    re_path(r'^budget/(?P<year>[0-9]{4})(?P<month>[0-9]{2})/$',
            login_required(BudgetView.as_view()),
            name='budget_select'),
    # path('charts', ChartsListView.as_view(), name='charts'),
    path('transactions', TransactionListView.as_view(), name='transactions'),
    path('new-transaction', TransactionCreateView.as_view(), name='new-transaction'),

    # Used for ajax updates
    path('update-transaction', views.update_transaction, name="update-transaction"),
    re_path(
        r'update-category|budget/(?P<year>[0-9]{4})(?P<month>[0-9]{2})/update-category',
        views.ajax_update,
        name="update-category"
    ),
    re_path(
        r'save-ordering|budget/*/save-ordering',
        views.save_ordering,
        name="update-order"
    ),
    path('reports', ReportsListView.as_view(), name='reports'),
    re_path(r'^reports/(?P<year>[0-9]{4})(?P<month>[0-9]{2})/$',
            login_required(ReportsListView.as_view()),
            name='reports_select'),
]

snaver/models.py
from datetime import date

from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _


class CustomUser(AbstractUser):
    name = models.CharField(_('User name'), max_length=255)
    email_confirmed = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.username}"

    def save(self, *args, **kwargs):
        is_new = self.pk is None
        super().save(*args, **kwargs)
        if is_new:
            Budget.objects.create(
                user=self,
                name=f"Default budget {self.name}"
            )


class Budget(models.Model):
    name = models.CharField(
        _('Budget name'),
        max_length=255,
        blank=False,
        validators=[MinLengthValidator(1)],
    )
    user = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        related_name='budgets',
    )

    created_on = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.name}"


class Category(models.Model):
    name = models.CharField(_('Category name'), max_length=255)
    budget = models.ForeignKey(
        Budget,
        on_delete=models.CASCADE,
        related_name='categories',
    )
    created_on = models.DateTimeField(default=timezone.now)
    order = models.IntegerField(blank=False, default=100_000)

    def __str__(self):
        return f"{self.name}"


class Subcategory(models.Model):
    name = models.CharField(_('Subcategory name'), max_length=255)
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        related_name='subcategories',
    )
    created_on = models.DateTimeField(default=timezone.now)
    order = models.IntegerField(blank=False, default=100_000)

    def __str__(self):
        return f"{self.name}"


class SubcategoryDetails(models.Model):
    budgeted_amount = models.DecimalField(
        _("Budgeted amount"),
        decimal_places=2,
        max_digits=12)
    start_date = models.DateField(_("Start date"))
    end_date = models.DateField(_("End date"))

    subcategory = models.ForeignKey(
        Subcategory,
        on_delete=models.CASCADE,
        related_name='details',
    )

    def save(self, *args, **kwargs):
        if self.start_date >= self.end_date:
            raise ValidationError(_("Start date must be before end date"))
        super(SubcategoryDetails, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.subcategory.name} - {self.start_date}"

    def is_past_due(self):
        return date.today() > self.end_date


class Transaction(models.Model):
    name = models.CharField(_('Transaction name'), max_length=255)

    payee_name = models.CharField(
        _('Payee name'),
        max_length=255,
        blank=True,
        null=True,
    )

    outflow = models.DecimalField(
        decimal_places=2,
        max_digits=11,
        default=0.00
    )
    inflow = models.DecimalField(
        decimal_places=2,
        max_digits=11,
        default=0.00
    )

    receipt_date = models.DateField(_('Receipt date'))

    subcategory = models.ForeignKey(
        Subcategory,
        on_delete=models.CASCADE,
        related_name='transactions',
    )

    created_on = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.name}"

project/templates/add-new.html
{% extends "layouts/base.html" %}
{% load mathfilters %}

{% block title %} New transaction {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}


    <div class="card-body">
        <form method="post">
            <table>
                {% csrf_token %}
                {{ form.as_table }}
            </table><br>
            <input type="submit" value="Save" class="btn btn-primary pull-center">
        </form>
    </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

project/templates/adding-transactions.html
{% extends "layouts/base.html" %}
{% load mathfilters %}

{% block title %} Transactions {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.css">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-primary">
                    <table class="table" id="transactiontable">
                        <tr>
                            <th>
                                <a href="{% url 'new-transaction' %}" title="Add new transaction"
                                   class="btn btn-primary pull-center">
                                    Add new transaction
                                </a>
                            </th>
                        </tr>
                    </table>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table" id="transactions">
                            <thead class="text-primary">
                            <tr style="cursor:pointer">
                                <th class="border-0">Date</th>
                                <th class="border-0">Description</th>
                                <th class="border-0">Payee</th>
                                <th class="border-0">Category</th>
                                <th class="border-0">Outflow</th>
                                <th class="border-0">Inflow</th>
                            </tr>
                            </thead>
                            <tbody id="transactions">
                            {% if transactions %}
                                {% for transaction in transactions.transaction_list %}
                                    <tr>
                                        <td class="border-0 editable-date date" data-id="{{ transaction.id }}"
                                            data-type="transaction_date">{{ transaction.receipt_date|date:"c" }}
                                        </td>
                                        <td class="border-0 editable" data-id="{{ transaction.id }}"
                                            data-type="transaction_name">{{ transaction.name }}
                                        </td>
                                        <td class="border-0 editable" data-id="{{ transaction.id }}"
                                            data-type="payee_name">{{ transaction.payee_name }}
                                        </td>
                                        <td class="border-0 " data-id="{{ transaction.id }}"
                                            data-type="transaction_subcategory">
                                            <select class="border-0 editable-list" id="select"
                                                    name="list_of_subcategories">
                                                <option selected
                                                        value="{{ transaction.subcategory.id }}">{{ transaction.subcategory.name }}</option>

                                                {% for subcategory in subcategory_list %}
                                                    <option value="{{ subcategory.id }}">{{ subcategory.name }}</option>
                                                {% endfor %}
                                            </select>
                                        </td>
                                        {#TODO:add inflow/outflow validation, add info about validation displayed to user#}
                                        <td class="border-0 editable" id="outflow" data-id="{{ transaction.id }}"
                                            data-type="outflow">{{ transaction.outflow }}
                                        </td>
                                        <td class="border-0 editable" id="inflow" data-id="{{ transaction.id }}"
                                            data-type="inflow">{{ transaction.inflow }}
                                        </td>
                                    </tr>
                                {% endfor %}
                            {% endif %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <button onclick="download_csv_file()" class="btn btn-primary pull-center"
                title="Export all transactions to csv file with just one clik">Download CSV file</button>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
    <script>
        $(document).ready(function () {
            $('#transactions').DataTable({
                "columnDefs": [
                    {"searchable": false, "targets": 3}
                ],
                language: {
                    searchPlaceholder: "in transactions"
                },
                "order": [[0, "desc"]],
            });
        });

        $(document).ready(function () {
            $(document).on("click", ".editable", function () {
                let value = $(this).text()
                let input = '<input type="text" tabindex="0" class="input-data form-control" value="' + value + '">';
                $(this).html(input);
                $(this).removeClass("editable");
                $('.input-data').focus();
            });

            $(document).on("click", ".editable-date", function () {
                let value = $(this).text()
                let input = '<input type="date" tabindex="0" class="input-data form-control" value=' + value + '>';
                $(this).html(input);
                $(this).removeClass("editable-date");
                $('.input-data').focus();
            });

            $(document).on("blur", "#select", function () {
                console.log("lost focus");
                let value = $(this).find("option:selected").attr('value');
                let td = $(this).parent("td");
                let id = td.data('id');
                let type = td.data('type');
                sendToServer(id, value, type);
            });


            $(document).on("keypress", ".input-data", function (e) {
                let key = e.which;
                if (key == 13) {
                    console.log("lost focus");
                    let value = $(this).val();
                    let td = $(this).parent("td");
                    let type = td.data('type')
                    sendToServer(td.data(id), value, type);
                }
            });

            $(document).on("blur", ".input-data", function () {
                console.log("lost focus");
                let value = $(this).val();
                let td = $(this).parent("td");
                let id = td.data('id')
                let type = td.data('type')
                sendToServer(id, value, type);
            });


            function sendToServer(id, value, type) {
                console.log(id);
                console.log(value);
                console.log(type);

                $.ajax({
                    url: "update-transaction",
                    type: "POST",
                    data: {id: id, type: type, value: value}
                })
                    .done(function (response) {
                        console.log(response);
                        $('body').load("");
                    })
                    .fail(function () {
                        console.log("Error occurred")
                    });
            }

        });
    </script>


    <script>
        //create CSV file data in an array
        var csvFileData = [
            {% for transaction in transactions.transaction_list %}
                [
                    '{{ transaction.receipt_date }}',
                    '{{ transaction.name }}',
                    '{{ transaction.payee_name }}',
                    '{{ transaction.subcategory.name }}',
                    '{{ transaction.outflow }}',
                    '{{ transaction.inflow }}',
                ],
            {% endfor %}
        ];

        //create a user-defined function to download CSV file
        function download_csv_file() {

            //define the heading for each row of the data
            var csv = 'DATE;DESCRIPTION;PAYEE;CATEGORY;OUTFLOW;INFLOW\n';

            //merge the data with CSV
            csvFileData.forEach(function (row) {
                csv += row.join(';');
                csv += "\n";
            });

            var hiddenElement = document.createElement('a');
            hiddenElement.href = 'data:text/csv;charset=utf-8,' + encodeURI(csv);
            hiddenElement.target = '_blank';

            //provide the name for the CSV file to be downloaded
            hiddenElement.download = 'Snaver_transactions.csv';
            hiddenElement.click();
        }
    </script>

{% endblock javascripts %}

project/templates/charts.html
{% extends "layouts/base.html" %}
{% load mathfilters %}

{% block title %} Charts {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <a href="{% url "charts_select" prev_month.year prev_month.month|stringformat:"02d" %}">
        <button class="btn btn-primary btn-round">&lt;</button>
    </a>
    {{ view.kwargs.year }}-{{ view.kwargs.month }}
    <a href="{% url "charts_select" next_month.year next_month.month|stringformat:"02d" %}">
        <button class="btn btn-primary btn-round">&gt;</button>
    </a>

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-primary">
                    <h4 class="card-title ">Charts for your budget</h4>
                    <p class="card-category">in {{ view.kwargs.year }}-{{ view.kwargs.month }}</p>
                </div>
                <div class="card-body">

                    <h3>CHART FOR SUBCATEGORIES AGAINST <b>BUDGETED AMOUNTS</b></h3>
                    <p>Total budgeted amount: {{ object_list.2 }}</p>
                    <div class="progress-container">
                        {% for details in object_list.0 %}
                            {% with a=details.budgeted_amount b=object_list.2 %}
                                {% with value=a|div:b|mul:100 %}
                                    <!-- calculating the percentage value to the progress-bar -->
                                    <span class="progress-badge">{{ details.subcategory.name }}: {{ details.budgeted_amount }}</span>
                                    <div class="progress">
                                        <div class="progress-bar bg-success" role="progressbar"
                                             aria-valuenow="{{ value }}" aria-valuemin="0"
                                             aria-valuemax="100" style="width: {{ value }}%;">
                                        </div>
                                    </div>
                                {% endwith %}
                            {% endwith %}
                        {% endfor %}
                    </div>
                    <br>
                    <br>
                    <br>

                    <h3>CHART FOR SUBCATEGORIES AGAINST <b>EXPENSES</b></h3>
                    <p>Total expenses: {{ object_list.1 }}</p>
                    <div class="progress-container">
                        {% for details in object_list.0 %}
                            {% with a=details.activity b=object_list.2 %}
                                {% with value=a|div:b|mul:100 %}
                                    <!-- calculating the percentage value to the progress-bar -->
                                    <span class="progress-badge">{{ details.subcategory.name }}: {{ details.activity }}</span>
                                    <div class="progress">
                                        <div class="progress-bar" role="progressbar" aria-valuenow="{{ value }}"
                                             aria-valuemin="0"
                                             aria-valuemax="100" style="width: {{ value }}%;">
                                        </div>
                                    </div>
                                {% endwith %}
                            {% endwith %}
                        {% endfor %}
                    </div>
                    <br>
                    <br>
                    <br>
                </div>
            </div>
        </div>
    </div>



{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

    <script>
        $(document).ready(function () {
            // Javascript method's body can be found in assets/js/demos.js
            md.initDashboardPageCharts();

        });
    </script>

{% endblock javascripts %}

project/templates/page-403.html
{% extends "layouts/base.html" %}

{% block title %} Page 404 {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card card-profile">
                <div class="card-body">
                    <h6 class="card-category text-gray">Error 403</h6>
                    <h4 class="card-title">
                        Access Denied
                    </h4>
                    <a href="/" class="btn btn-primary btn-round">Home</a>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

project/templates/page-404.html
{% extends "layouts/base.html" %}

{% block title %} Page 404 {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card card-profile">
                <div class="card-body">
                    <h6 class="card-category text-gray">Error 404</h6>
                    <h4 class="card-title">
                        Page not found
                    </h4>
                    <a href="/" class="btn btn-primary btn-round">Home</a>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

project/templates/page-500.html
{% extends "layouts/base.html" %}

{% block title %} Page 404 {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card card-profile">
                <div class="card-body">
                    <h6 class="card-category text-gray">Error 500</h6>
                    <h4 class="card-title">
                        Internal Server Error
                    </h4>
                    <a href="/" class="btn btn-primary btn-round">Home</a>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

project/templates/page-user.html
{% extends "layouts/base.html" %}

{% block title %}- Profile Page {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header card-header-primary">
                    <h4 class="card-title">{{ user.username }} - Profile</h4>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <label class="bmd-label-floating">Username</label>
                                <input type="text" class="form-control" disabled value="{{ request.user.username }}">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="bmd-label-floating">Email address</label>
                                <input type="email" class="form-control" disabled value="{{ request.user.email }}">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="bmd-label-floating">Date joined</label>
                                <input type="email" class="form-control" disabled
                                       value="{{ request.user.date_joined }}">
                            </div>
                        </div>
                    </div>
                    <br>
                    <div>
                        <ul>
                            <li><a href="{% url 'email_change' user.id %}" class="text-primary">Change email</a>
                            </li>
                            <li><a href="{% url 'password_change' %}" class="text-primary">Change password</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

project/templates/ui-icons.html
{% extends "layouts/base.html" %}

{% block title %} UI Icons {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

        <div class="container-fluid">
            <div class="card card-plain">
              <div class="card-header card-header-primary">
                <h4 class="card-title">Material Design Icons</h4>
                <p class="card-category">Handcrafted by our friends from
                  <a target="_blank" href="https://design.google.com/icons/">Google</a>
                </p>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <div class="card-body">
                    <div class="iframe-container d-none d-lg-block">
                      <iframe src="https://design.google.com/icons/">
                        <p>Your browser does not support iframes.</p>
                      </iframe>
                    </div>
                    <div class="col-md-12 d-none d-sm-block d-md-block d-lg-none d-block d-sm-none text-center ml-auto mr-auto">
                      <h5>The icons are visible on Desktop mode inside an iframe. Since the iframe is not working on Mobile and Tablets please visit the icons on their original page on Google. Check the
                        <a href="https://design.google.com/icons/" target="_blank">Material Icons</a>
                      </h5>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

project/templates/ui-maps.html
{% extends "layouts/base.html" %}

{% block title %} Maps {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div id="map"></div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <script>
    $(document).ready(function() {
      // Javascript method's body can be found in assets/js/demos.js
      demo.initGoogleMaps();
    });
  </script>
  
{% endblock javascripts %}

project/templates/ui-tables.html
{% extends "layouts/base.html" %}
{% load mathfilters %}

{% block title %} Budget {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-primary">
                    <h4 class="card-title ">Current month categories</h4>
                    <p class="card-category"> A list of your activities in {% now "F" %}</p>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table">
                            <thead class=" text-primary">
                            <tr>
                                <th>Category name</th>
                                <th>Subcategory name</th>
                                <th>Budgeted</th>
                                <th>Activity</th>
                                <th>Available</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for details in object_list %}
                                <tr>
                                    <td>{{ details.subcategory.category.name }}</td>
                                    <td>{{ details.subcategory.name }}</td>
                                    <td>{{ details.budgeted_amount }}</td>
                                    <td>{{ details.activity }}</td>
                                    {% if details.available < 0 %}
                                        <td class="negative-activity">
                                            {% else %}
                                        <td class="positive-activity">
                                    {% endif %}
                                    {% if details.available == None %}
                                        {{ details.budgeted_amount }}</td>
                                            {% else %}
                                        {{ details.available }}</td>
                                    {% endif %}
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}